// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD81khwEfmLEnxeHijAj6jGpXNHx5ZGJm8',
    appId: '1:422392390863:web:215439242cd377461903ba',
    messagingSenderId: '422392390863',
    projectId: 'localeats-12b4c',
    authDomain: 'localeats-12b4c.firebaseapp.com',
    storageBucket: 'localeats-12b4c.firebasestorage.app',
    measurementId: 'G-FJ69KCXKT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1uD1GpZFoA89RZIxFUKIpl14wLMcHph4',
    appId: '1:422392390863:android:e166f900479a9dd61903ba',
    messagingSenderId: '422392390863',
    projectId: 'localeats-12b4c',
    storageBucket: 'localeats-12b4c.firebasestorage.app',
  );
}
