name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
      - name: Get dependencies
        run: |
          cd localeats
          flutter pub get
      - name: Build APK
        run: |
          cd localeats
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: localeats/build/app/outputs/flutter-apk/app-release.apk
